ZEL-2171 add request id middleware
zelusio/nitro-secure-service pull request #38
Opened 2024-10-24 14:04 UTC by vm-vchyypesh

2024-10-24 14:14 UTC, vm-vhryschenko submitted a review, later dismissed

2024-10-24 14:14 UTC, aleksei-yudin approved these changes, later dismissed

2024-10-24 19:08 UTC, K-Mistele requested changes

2024-10-24 19:08 UTC, K-Mistele commented on src/services/exportWallet.service.ts
> +        'nss-auth': `Bearer ${nssToken}`,
Using non-standard HTTP headers is fine, we just need to make sure to use them correctly. Non-standard headers should be prefixed with `X-` e.g. `X-Nss-Auth`

2024-10-25 10:18 UTC, aleksei-yudin approved these changes

2024-10-25 20:00 UTC, K-Mistele commented
Does `X-Nss-Auth` need to be in the trusted headers list as well?

2024-10-26 15:51 UTC, vm-vchyypesh commented
> Does `X-Nss-Auth` need to be in the trusted headers list as well?

`X-Nss-Auth` header is similar to `authorization`, so it shouldn't be in trusted list.

https://docs.evervault.com/primitives/enclaves/reference#trusted-headers

2024-10-31 22:35 UTC, K-Mistele approved these changes

2024-10-31 22:35 UTC, merged